import { utilService } from './util.service'
export const defaultInfo = {
  loggedinUser: loggedinUser(),
  emails: emails(),
}

function loggedinUser() {
  return {
    email: 'user@appsus.com',
    fullName: 'Mahatma Appsus',
  }
}
function emails() {
  return ([
    {
      id: utilService.makeId(),
      subject: 'Miss you',
      body: 'Would love to catch up sometimes',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1551133930594,
      removedAt: null,
      from: 'momo@momo.com',
      fullName: 'Momo Williams',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'What do you do to get rid of stress?',
      body: 'Thrown shy denote ten ladies though ask saw.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1243468800000,
      removedAt: null,
      from: 'mark.sweeney@comcast.net',
      fullName: 'Mark Grant',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: "What's your favorite way to waste time?",
      body: 'Insipidity the sufficient discretion imprudence resolution sir him decisively.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1280275200000,
      removedAt: null,
      from: 'zz5djndn6f86sa8@ymail.com',
      fullName: 'Bob Lucas',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'When you describe yourself to others, what words do you use?',
      body: ' Explained propriety off out perpetual his you.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1305676800000,
      removedAt: null,
      from: 'ubayd.avery@outlook.com',
      fullName: 'Ubayd Benson',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject:
        'What kind of case do you have for your phone? Why did you choose it?',
      body: 'By an outlived insisted procured improved am.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1404432000000,
      removedAt: null,
      from: 'sscewwvjyht@gmail.com',
      fullName: 'Vincent Clark',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'How was your weekend?',
      body: 'Wished he entire esteem of mr oh.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1220275200000, // 1 year before the earliest email
      removedAt: null,
      from: 'emily.watson@hotmail.com',
      fullName: 'Emily Watson',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'What do you like to do in your free time?',
      body: 'Inquietude simplicity terminated she compliment.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1255676800000,
      removedAt: null,
      from: 'lucas.brown@aol.com',
      fullName: 'Lucas Brown',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'Have you traveled anywhere exciting recently?',
      body: 'Unpleasant nor diminution excellence apartments.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1264432000000,
      removedAt: null,
      from: 'arah.taylor@yahoo.com',
      fullName: 'Sarah Taylor',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'What kind of music do you like?',
      body: 'In as of old insipidity ask parties.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1270275200000,
      removedAt: null,
      from: 'james.davis@gmail.com',
      fullName: 'James Davis',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'Do you have any fun plans for the weekend?',
      body: 'Unpleasant especially as contrasted unfeeling.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1285676800000,
      removedAt: null,
      from: 'olivia.lee@hotmail.com',
      fullName: 'Olivia Lee',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'What do you like to do to relax?',
      body: 'Unpleasant especially as contrasted unfeeling.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1294432000000,
      removedAt: null,
      from: 'william.hall@aol.com',
      fullName: 'William Hall',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'Have you seen any good movies lately?',
      body: 'Inquietude simplicity terminated she compliment.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1300275200000,
      removedAt: null,
      from: 'hannah.martin@yahoo.com',
      fullName: 'Hannah Martin',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'What do you like to do on a rainy day?',
      body: 'Unpleasant nor diminution excellence apartments.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1315676800000,
      removedAt: null,
      from: 'daniel.white@hotmail.com',
      fullName: 'Daniel White',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'Do you have any pets?',
      body: 'Explained propriety off out perpetual his you.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1324432000000,
      removedAt: null,
      from: 'jessica.parker@aol.com',
      fullName: 'Jessica Parker',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'How was your weekend?',
      body: 'Wished he entire happiness resolving continued.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: Date.now() - 31536000000, // 1 year ago
      removedAt: null,
      from: 'james.brown@yahoo.com',
      fullName: 'James Brown',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'What do you like to do in your free time?',
      body: 'Inquietude simplicity terminated she compliment.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: Date.now() - 25920000000, // 9 months ago
      removedAt: null,
      from: 'emily.davis@hotmail.com',
      fullName: 'Emily Davis',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'Have you traveled anywhere exciting recently?',
      body: 'Unpleasant nor diminution excellence apartments.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: Date.now() - 15552000000, // 6 months ago
      removedAt: null,
      from: 'olivia.martin@aol.com',
      fullName: 'Olivia Martin',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'What are your favorite hobbies?',
      body: 'Unpleasant impossible he consideration sincerity.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: Date.now() - 7776000000, // 3 months ago
      removedAt: null,
      from: 'harrison.white@gmail.com',
      fullName: 'Harrison White',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'How was your morning?',
      body: 'Unpleasant impossible he consideration sincerity.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: Date.now() - 2592000000, // 30 days ago
      removedAt: null,
      from: 'ophia.patel@yahoo.com',
      fullName: 'Sophia Patel',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: "Let's collaborate on a project",
      body: 'I think our skills would complement each other well.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1617026430594,
      removedAt: null,
      from: 'sarah.jones@gmail.com',
      fullName: 'Sarah Johnson',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'Question about your recent post',
      body: 'I really enjoyed your article on sustainable living. Do you have any recommendations for eco-friendly household products?',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1648454400000,
      removedAt: null,
      from: 'john.doe@yahoo.com',
      fullName: 'John Doe',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'Invitation to networking event',
      body: 'I think you would really benefit from attending this upcoming networking event for local entrepreneurs.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1620530400000,
      removedAt: null,
      from: 'networking@eventbrite.com',
      fullName: 'Networking Events',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'Follow-up on job application',
      body: 'I wanted to follow up on my job application for the marketing position at your company. Have you had a chance to review my resume?',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1643026430594,
      removedAt: null,
      from: 'jane.smith@gmail.com',
      fullName: 'Jane Smith',
      to: loggedinUser.email,
    },
    {
      id: utilService.makeId(),
      subject: 'Recommendation for a good book',
      body: 'I recently read a great book that I think you would enjoy. It\'s called "The Power of Now" by Eckhart Tolle.',
      isRead: false,
      isStarred: false,
      inTrash: false,
      onDraft: false,
      sentAt: 1635644800000,
      removedAt: null,
      from: 'alice.wonderland@gmail.com',
      fullName: 'Alice Wonderland',
      to: loggedinUser.email,
    },
  ])
}
